### ISSUE TITLE
cocotb make中错误

### ISSUE THREAD

**Issue by sinceseto** [Groupsun/CCPA-2020-LAB#20]
尝试用第0章pdf里的例子测试环境，请问这怎么解决？
makefile内容如下
```
VERILOG_SOURCES = $(PWD)/FullAdder.v
TOPLEVEL = FullAdder
MODULE = fulladder_test
SIM = verilator
EXTRA_ARGS += --trace

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
```
make中的错误
```
make results.xml
make[1]: 进入目录“/home/wyf/文档/计组实验/tests”
PYTHONPATH=/home/wyf/文档/计组实验/tests/build/libs/x86_64:/home/wyf/文档/计组实验/tests:/home/wyf/.local/lib/python3.8/site-packages: LD_LIBRARY_PATH=/home/wyf/文档/计组实验/tests/build/libs/x86_64 LD_LIBRARY_PATH=/home/wyf/文档/计组实验/tests/build/libs/x86_64::/usr/lib:/usr/lib:/usr/lib:/usr/lib MODULE=fulladder_test \
        TESTCASE= TOPLEVEL=FullAdder TOPLEVEL_LANG= COCOTB_SIM=1 \
        sim_build/FullAdder 
     -.--ns INFO     cocotb.gpi                                  gpi_embed.c:78   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     cocotb.gpi                                GpiCommon.cpp:104  in gpi_print_registered_impl       VPI registered
     0.00ns INFO     cocotb.gpi                                  gpi_embed.c:340  in embed_sim_init                  Running on Verilator version 4.028 2020-02-06
     0.00ns INFO     cocotb.gpi                                  gpi_embed.c:341  in embed_sim_init                  Python interpreter initialized and cocotb loaded!
     0.00ns INFO     cocotb                                      __init__.py:137  in _initialise_testbench           Running tests with cocotb v1.3.1 from /home/wyf/.local/lib/python3.8/site-packages
     0.00ns INFO     cocotb                                      __init__.py:155  in _initialise_testbench           Seeding Python random module with 1589815835
     0.00ns CRITICAL cocotb.regression                         regression.py:137  in initialise                      Failed to import module fulladder_test: No module named 'fulladder_test'
     0.00ns INFO     cocotb.regression                         regression.py:138  in initialise                      MODULE variable was "fulladder_test"
     0.00ns INFO     cocotb.regression                         regression.py:139  in initialise                      Traceback: 
     0.00ns INFO     cocotb.regression                         regression.py:140  in initialise                      Traceback (most recent call last):
                                                                                                                       File "/home/wyf/.local/lib/python3.8/site-packages/cocotb/regression.py", line 135, in initialise
                                                                                                                         module = _my_import(module_name)
                                                                                                                       File "/home/wyf/.local/lib/python3.8/site-packages/cocotb/regression.py", line 63, in _my_import
                                                                                                                         mod = __import__(name)
                                                                                                                     ModuleNotFoundError: No module named 'fulladder_test'
                                                                                                                     
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/home/wyf/.local/lib/python3.8/site-packages/cocotb/__init__.py", line 175, in _initialise_testbench
    regression_manager.initialise()
  File "/home/wyf/.local/lib/python3.8/site-packages/cocotb/regression.py", line 135, in initialise
    module = _my_import(module_name)
  File "/home/wyf/.local/lib/python3.8/site-packages/cocotb/regression.py", line 63, in _my_import
    mod = __import__(name)
ModuleNotFoundError: No module named 'fulladder_test'
     0.00ns ERROR    cocotb.gpi                                  gpi_embed.c:425  in embed_sim_init                  cocotb initialization failed - exiting
     0.00ns ERROR    cocotb.scheduler                            __init__.py:198  in _sim_event                      Failing test at simulator request before test run completion: Simulator shutdown prematurely
```

**Comment by Groupsun** [comment]
> `Failed to import module fulladder_test: No module named 'fulladder_test'`

错误原因错在这里，你的python harness文件叫什么名字，是否确认是`fulladder_test.py`

**Comment by sinceseto** [comment]
> > `Failed to import module fulladder_test: No module named 'fulladder_test'`
> 
> 错误原因错在这里，你的python harness文件叫什么名字，是否确认是`fulladder_test.py`

确实是这里错了，已解决，谢谢。
